// Mock Game Data

export const BATTLE_POSTS = [
  {
    id: '1',
    platform: 'facebook',
    username: 'Tin Tức Nhanh 247',
    avatar: 'https://i.pravatar.cc/150?img=1',
    time: '2 giờ trước',
    content: '🚨 KHẨN CẤP: Uống nước chanh mỗi sáng giúp tiêu diệt 99% tế bào ung thư! Các bác sĩ không muốn bạn biết điều này!',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&q=80',
    likes: 45200,
    shares: 12800,
    comments: 3400,
    correctAnswer: 'fake',
    explanation: 'Đây là thông tin sai lệch điển hình. Không có bằng chứng khoa học nào chứng minh nước chanh "tiêu diệt ung thư". Tiêu đề sử dụng kỹ thuật clickbait và conspiracy theory.',
    clues: ['Tiêu đề giật tít quá mức', 'Không có nguồn khoa học', 'Dùng từ "các bác sĩ không muốn bạn biết"'],
  },
  {
    id: '2',
    platform: 'tiktok',
    username: '@baochinhphu.vn',
    avatar: 'https://i.pravatar.cc/150?img=5',
    time: '1 ngày trước',
    content: 'Chính phủ thông qua nghị định mới về bảo vệ người tiêu dùng trên thương mại điện tử, có hiệu lực từ tháng 7/2025.',
    image: 'https://images.unsplash.com/photo-1604328698692-f76ea9498e76?w=400&q=80',
    likes: 8900,
    shares: 1200,
    comments: 450,
    correctAnswer: 'real',
    explanation: 'Đây là thông tin thật từ nguồn chính thức. Báo Chính phủ là nguồn tin cậy, nội dung có thể kiểm chứng.',
    clues: ['Nguồn chính thống', 'Nội dung cụ thể, có số liệu', 'Không có ngôn ngữ cảm xúc quá mức'],
  },
  {
    id: '3',
    platform: 'instagram',
    username: 'health_viet_nam',
    avatar: 'https://i.pravatar.cc/150?img=3',
    time: '5 giờ trước',
    content: 'NGHIÊN CỨU MỚI: Vaccine COVID-19 khiến DNA thay đổi vĩnh viễn! Share ngay cho mọi người biết! 😱😱',
    image: 'https://images.unsplash.com/photo-1584483766114-2cea6facdf57?w=400&q=80',
    likes: 23000,
    shares: 18000,
    comments: 7800,
    correctAnswer: 'fake',
    explanation: 'Đây là thông tin sai hoàn toàn. mRNA vaccine không thể thay đổi DNA vì không có cơ chế nào cho phép điều đó xảy ra.',
    clues: ['Chữ in hoa toàn bộ', 'Kêu gọi share gấp', 'Không có link nghiên cứu cụ thể'],
  },
  {
    id: '4',
    platform: 'facebook',
    username: 'Cộng đồng Chia Sẻ',
    avatar: 'https://i.pravatar.cc/150?img=7',
    time: '3 giờ trước',
    content: '"Giá xăng sắp tăng 5000đ/lít" - Theo nguồn tin không chính thức từ Bộ Công Thương',
    image: 'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&q=80',
    likes: 3200,
    shares: 890,
    comments: 234,
    correctAnswer: 'misleading',
    explanation: '"Nguồn tin không chính thức" không phải là nguồn. Thông tin có thể gây hoang mang, thiếu căn cứ xác thực.',
    clues: ['Nguồn mơ hồ "không chính thức"', 'Gây tâm lý lo lắng', 'Không có ngày cụ thể'],
  },
  {
    id: '5',
    platform: 'tiktok',
    username: 'deepfake_detector',
    avatar: 'https://i.pravatar.cc/150?img=9',
    time: '6 giờ trước',
    content: 'VIDEO: Ca sĩ nổi tiếng tuyên bố ủng hộ sản phẩm X trong đoạn clip lan truyền 🎵',
    image: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&q=80',
    likes: 67000,
    shares: 23000,
    comments: 12000,
    correctAnswer: 'ai_generated',
    explanation: 'Clip này được tạo bằng công nghệ deepfake. Dấu hiệu: ánh sáng không đồng đều quanh khuôn mặt, khẩu hình miệng không khớp hoàn toàn.',
    clues: ['Ánh sáng khuôn mặt bất thường', 'Khẩu hình không khớp', 'Không có tuyên bố chính thức từ nghệ sĩ'],
  },
  {
    id: '6',
    platform: 'instagram',
    username: 'viral.news.vn',
    avatar: 'https://i.pravatar.cc/150?img=11',
    time: '8 giờ trước',
    content: 'Bức ảnh này được chụp tại trận lũ lụt ở Hà Nội tuần qua 😢 Chia sẻ để ủng hộ bà con!',
    image: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=400&q=80',
    likes: 89000,
    shares: 45000,
    comments: 8900,
    correctAnswer: 'context',
    explanation: 'Ảnh này thực sự là từ trận lũ ở Thái Lan năm 2022, không phải Hà Nội. Đây là kỹ thuật "cut context" - dùng ảnh thật nhưng sai bối cảnh.',
    clues: ['Kiểm tra reverse image search', 'Biển số xe/chữ viết trên ảnh', 'Thực vật/kiến trúc không khớp'],
  },
];

export const INVESTIGATION_CASES = [
  {
    id: '1',
    title: 'Vụ Án: Video Ngập Lụt Giả Mạo',
    difficulty: 'Dễ',
    xpReward: 150,
    timeLimit: 300,
    description: 'Một video lan truyền tuyên bố quay cảnh ngập lụt tại TP.HCM. Hãy điều tra sự thật.',
    evidence: [
      { type: 'image', label: 'Ảnh chụp màn hình video', url: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?w=600&q=80' },
      { type: 'metadata', label: 'Metadata tệp', data: { 'Ngày tạo': '2022-08-15', 'Thiết bị': 'iPhone 12', 'Vị trí GPS': 'Bangkok, Thailand', 'Phần mềm': 'Adobe Premiere' } },
      { type: 'text', label: 'Caption gốc', content: 'Ngập lụt kinh hoàng tại TP.HCM ngày hôm nay! Người dân cần sơ tán khẩn!' },
    ],
    verdict: 'context',
    verdictExplanation: 'Video thật sự nhưng từ Bangkok 2022. Metadata GPS tiết lộ vị trí thật. Adobe Premiere cho thấy đã qua chỉnh sửa.',
  },
  {
    id: '2',
    title: 'Vụ Án: Deepfake CEO Gian Lận',
    difficulty: 'Trung Bình',
    xpReward: 300,
    timeLimit: 480,
    description: 'Một video của CEO tập đoàn lớn tuyên bố phá sản lan truyền và làm cổ phiếu giảm mạnh.',
    evidence: [
      { type: 'image', label: 'Frame phân tích khuôn mặt', url: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=600&q=80' },
      { type: 'metadata', label: 'Phân tích AI', data: { 'Xác suất Deepfake': '94.7%', 'Pixel inconsistency': 'Cao', 'Khẩu hình khớp': '67%', 'Blending artifacts': 'Có' } },
      { type: 'text', label: 'Tuyên bố chính thức', content: 'Công ty khẳng định không có buổi họp báo nào vào ngày đó.' },
    ],
    verdict: 'ai_generated',
    verdictExplanation: 'Deepfake với 94.7% xác suất AI tạo. Pixel inconsistency và blending artifacts rõ ràng khi phân tích frame-by-frame.',
  },
];

export const SKILLS = [
  // Free Basic Skills
  {
    id: 'clickbait',
    name: 'Nhận Diện Clickbait',
    icon: '🎣',
    level: 'Cơ Bản',
    isPremium: false,
    isUnlocked: true,
    xpRequired: 0,
    description: 'Học cách nhận biết tiêu đề giật tít, câu view không có nội dung thực.',
    lessons: 5,
    completedLessons: 3,
    color: '#00F5FF',
  },
  {
    id: 'source_check',
    name: 'Kiểm Tra Nguồn Tin',
    icon: '🔍',
    level: 'Cơ Bản',
    isPremium: false,
    isUnlocked: true,
    xpRequired: 100,
    description: 'Cách xác minh độ tin cậy của nguồn thông tin trực tuyến.',
    lessons: 6,
    completedLessons: 1,
    color: '#00FF88',
  },
  {
    id: 'headline_analysis',
    name: 'Phân Tích Tiêu Đề',
    icon: '📰',
    level: 'Cơ Bản',
    isPremium: false,
    isUnlocked: true,
    xpRequired: 200,
    description: 'Đọc tiêu đề thông minh, không bị dắt mũi bởi ngôn ngữ cảm xúc.',
    lessons: 4,
    completedLessons: 0,
    color: '#FFD700',
  },
  {
    id: 'basic_ai_detect',
    name: 'Phát Hiện Ảnh AI',
    icon: '🤖',
    level: 'Cơ Bản',
    isPremium: false,
    isUnlocked: false,
    xpRequired: 500,
    description: 'Nhận biết hình ảnh được tạo bởi AI thông qua các dấu hiệu cơ bản.',
    lessons: 7,
    completedLessons: 0,
    color: '#7B2FFF',
  },
  // Premium Advanced Skills
  {
    id: 'deepfake_advanced',
    name: 'Phân Tích Deepfake',
    icon: '🎭',
    level: 'Nâng Cao',
    isPremium: true,
    isUnlocked: false,
    xpRequired: 1000,
    description: 'Kỹ thuật phân tích frame-by-frame, pixel inconsistency, audio sync để phát hiện deepfake.',
    lessons: 10,
    completedLessons: 0,
    color: '#FF006E',
  },
  {
    id: 'psych_manipulation',
    name: 'Thao Túng Tâm Lý',
    icon: '🧠',
    level: 'Nâng Cao',
    isPremium: true,
    isUnlocked: false,
    xpRequired: 1500,
    description: 'Hiểu cách truyền thông thao túng cảm xúc, thiên kiến nhận thức và confirmation bias.',
    lessons: 12,
    completedLessons: 0,
    color: '#FF006E',
  },
  {
    id: 'bias_analysis',
    name: 'Phân Tích Bias',
    icon: '⚖️',
    level: 'Nâng Cao',
    isPremium: true,
    isUnlocked: false,
    xpRequired: 2000,
    description: 'Nhận diện thiên vị trong báo chí, mạng xã hội và thuật toán.',
    lessons: 8,
    completedLessons: 0,
    color: '#FF6B00',
  },
  {
    id: 'osint',
    name: 'OSINT Cơ Bản',
    icon: '🕵️',
    level: 'Chuyên Gia',
    isPremium: true,
    isUnlocked: false,
    xpRequired: 3000,
    description: 'Kỹ năng tình báo nguồn mở: reverse image search, geolocation, timeline verification.',
    lessons: 15,
    completedLessons: 0,
    color: '#00F5FF',
  },
];

export const LEADERBOARD = [
  { rank: 1, name: 'TruthHunter_VN', xp: 45820, level: 42, badge: '💎', streak: 89 },
  { rank: 2, name: 'MinhDetective', xp: 38900, level: 36, badge: '💎', streak: 62 },
  { rank: 3, name: 'FactChecker2025', xp: 35100, level: 33, badge: '🥇', streak: 44 },
  { rank: 4, name: 'AnhTran_Saigon', xp: 29400, level: 28, badge: '🥇', streak: 31 },
  { rank: 5, name: 'LinhMediaLit', xp: 24800, level: 23, badge: '🥈', streak: 27 },
  { rank: 6, name: 'CyberSherlockVN', xp: 21200, level: 20, badge: '🥈', streak: 19 },
  { rank: 7, name: 'TuanDebunker', xp: 18600, level: 18, badge: '🥉', streak: 15 },
  { rank: 8, name: 'HaNoiTruth', xp: 15300, level: 15, badge: '🥉', streak: 12 },
  { rank: 9, name: 'NamNewsNerd', xp: 12100, level: 12, badge: '🥉', streak: 8 },
  { rank: 10, name: 'ThaoMediaQ', xp: 9800, level: 10, badge: '🥉', streak: 5 },
];

export const DAILY_CHALLENGES = [
  {
    id: 'dc1',
    title: 'Ngày Đại Chiến Clickbait',
    description: 'Phân loại 10 tiêu đề clickbait trong 5 phút',
    xpReward: 200,
    bonusXP: 50,
    difficulty: 'Dễ',
    timeLimit: 300,
    expiresIn: '14:23:00',
    icon: '🎣',
    color: '#00F5FF',
  },
];

export const VIDEOS = [
  {
    id: 'v1',
    title: 'Fake News là gì? Vì sao nó nguy hiểm?',
    duration: '4:32',
    thumbnail: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400&q=80',
    isPremium: false,
    category: 'Cơ Bản',
    views: '234K',
  },
  {
    id: 'v2',
    title: '5 Dấu Hiệu Nhận Biết Clickbait Ngay Lập Tức',
    duration: '6:15',
    thumbnail: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=400&q=80',
    isPremium: false,
    category: 'Cơ Bản',
    views: '189K',
  },
  {
    id: 'v3',
    title: 'Deepfake 2025: Không Thể Phân Biệt Bằng Mắt Thường',
    duration: '12:45',
    thumbnail: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400&q=80',
    isPremium: true,
    category: 'Nâng Cao',
    views: '98K',
  },
  {
    id: 'v4',
    title: 'Framework SIFT: Dừng, Điều Tra, Tìm Nguồn, Truy Xuất',
    duration: '9:20',
    thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&q=80',
    isPremium: true,
    category: 'Nâng Cao',
    views: '76K',
  },
  {
    id: 'v5',
    title: 'OSINT: Tìm Sự Thật Bằng Nguồn Mở',
    duration: '18:30',
    thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&q=80',
    isPremium: true,
    category: 'Chuyên Gia',
    views: '54K',
  },
];
